apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default 
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: frontend 
    repoURL: https://github.com/purushothamkdr453/argocd
    targetRevision: HEAD
