apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rbac
  name: rbac
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rbac
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rbac
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
